# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4  # Updated to the latest version
        with:
          node-version: 18  # Use a more recent Node.js version
      - name: Install node dependencies
        working-directory: ./server
        run: npm install
      
  client:
    needs: server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]  # Updated to the latest stable version (3.11)
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  # Updated to use the latest version
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        working-directory: ./client
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
